/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Pharmacist;

import ui.blood.*;
import business.BloodBank.BloodBank;
import business.BloodBank.BloodDirectory;
import ui.DoctorRole.*;
import business.Doctor.Doctor;
import business.Doctor.DoctorDirectorty;
import business.EcoSystem;
import business.Organization.BloodOrganization;
import business.Organization.DoctorOrganization;
import business.Organization.PharmacyOrganization;
import business.Pharmacy.Pharmacist;
import business.Pharmacy.PharmacyDirectory;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabTestWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class PharmacyOrgWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private PharmacyOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private Pharmacist currentPharmacist;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public PharmacyOrgWorkAreaJPanel(JPanel workArea, UserAccount account, PharmacyOrganization organization, EcoSystem business) {
        initComponents();

        this.workArea = workArea;
        this.organization = organization;
        this.business = business;
        this.userAccount = account;

        currentPharmacist = populatePharma();
        Time();
    }
    
    
     private void Time() {
       
                Date date= new Date();
                DateFormat timeFormat =  new SimpleDateFormat("HH:mm a");
                String time = timeFormat.format(date);
                timeLabel.setText(time);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Appointments = new javax.swing.JPanel();
        manageInventory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageDoctorRequest = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rightPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(249, 252, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeLabel.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        timeLabel.setText("3:45 PM");
        jPanel6.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setText("Pharmacy Dashboard");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 500, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        Appointments.setBackground(new java.awt.Color(255, 255, 255));
        Appointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageInventory.setBackground(new java.awt.Color(255, 255, 255));
        manageInventory.setPreferredSize(new java.awt.Dimension(100, 48));
        manageInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageInventoryMousePressed(evt);
            }
        });
        manageInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Manage Inventory");
        manageInventory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, -1));

        Appointments.add(manageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 60));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setPreferredSize(new java.awt.Dimension(100, 48));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Manage Profile");
        profile.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 20, 150, -1));

        Appointments.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        manageDoctorRequest.setBackground(new java.awt.Color(255, 255, 255));
        manageDoctorRequest.setPreferredSize(new java.awt.Dimension(100, 48));
        manageDoctorRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageDoctorRequestMousePressed(evt);
            }
        });
        manageDoctorRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Mange Doctor Request");
        manageDoctorRequest.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        Appointments.add(manageDoctorRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 60));
        Appointments.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pharmacy.jpg"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rightPanel.add(jLabel4, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Appointments, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        // TODO add your handling code here:
        //ad  appointments();

        updateProfile();
    }//GEN-LAST:event_profileMousePressed

    private void manageInventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageInventoryMousePressed

        manageInventory();
    }//GEN-LAST:event_manageInventoryMousePressed

    private void manageDoctorRequestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDoctorRequestMousePressed
        // TODO add your handling code here:

        manageDoctorRequest();
    }//GEN-LAST:event_manageDoctorRequestMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appointments;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel manageDoctorRequest;
    private javax.swing.JPanel manageInventory;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    private void updateProfile() {
        profile.setBackground(new Color(255, 255, 255));
        manageInventory.setBackground(new Color(213, 230, 249));
        manageDoctorRequest.setBackground(new Color(213, 230, 249));

        ManagePharmacyJPanel mphjp = new ManagePharmacyJPanel(workArea, userAccount, business, currentPharmacist);
        rightPanel.add(mphjp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }

    private Pharmacist populatePharma() {

        PharmacyDirectory directory = organization.getPharmacyDirectory();
        System.out.println("pharma : " + userAccount.getUsername());
        for (Pharmacist pharmacist : directory.getPharmaArrayList()) {
            if (pharmacist!=null && pharmacist.e!=null && pharmacist.e.getUserName()!=null && pharmacist.e.getUserName().equals(userAccount.getUsername())) {
                System.out.println("pharmacist found: " + pharmacist.e.getName());
                return pharmacist;
            }
        }

        System.out.println("pharmacist not found");
        return null;

    }

   

    private void manageDoctorRequest() {

        manageDoctorRequest.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));
        manageInventory.setBackground(new Color(213, 230, 249));

        ProcessOrderForPatient pofp = new ProcessOrderForPatient(workArea, userAccount, business, currentPharmacist);
        rightPanel.add(pofp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }

    private void manageInventory() {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        manageInventory.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));
        manageDoctorRequest.setBackground(new Color(213, 230, 249));

        PharmacistManageMedicines mpjp = new PharmacistManageMedicines(workArea, userAccount, business, currentPharmacist);

        rightPanel.add(mpjp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }
}
