/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PatientRole;

import business.Emergency.Emergency;
import business.Organization.EmergencyOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.Req_Emergency;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manal
 */
public class CheckEmergencyReqStatus extends javax.swing.JPanel {

    /**
     * Creates new form CheckEmergencyReqStatus
     */
    private JPanel userProcessContainer;

    private UserAccount userAccount;
    private EmergencyOrganization emergencyOrganization;
    
    public CheckEmergencyReqStatus(JPanel userProcessContainer, UserAccount account, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.emergencyOrganization = (EmergencyOrganization) organization;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtablemed = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        jtablemed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtablemed.setGridColor(new java.awt.Color(255, 255, 255));
        jtablemed.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jtablemed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablemedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablemed);

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("View Emergency Requests");

        btnRefresh.setBackground(new java.awt.Color(255, 55, 95));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtablemedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablemedMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtablemedMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtablemed.getModel();

        model.setRowCount(0);
        System.out.println("emergencyOrganization.getReqEmgDir().getEmergencyUserList()" + emergencyOrganization);
        for (Req_Emergency request : emergencyOrganization.getReqEmgDir().getEmergencyUserList()) {
            Emergency requestEmg = request.getEmergencyID(); // Get the Lab associated with the request
            // System.out.println("requestLab: " + requestLab);
            //  System.out.println("user name is****" + userAccount.getUsername());
            if (requestEmg != null && requestEmg.getEmergencyID().equals(userAccount.getUsername())) {

                //System.out.println("request: " + request);
                Object[] row = new Object[5];
                row[0] = request; // Storing the object reference in row[0]
                row[1] = request.getUserId().getUsername(); // Displayed in the table
                row[2] = request.getLocation(); // Displayed in the table
                row[3] = request.getStatus();

// Add row to the table model
                  model.addRow(row);

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablemed;
    // End of variables declaration//GEN-END:variables
}
