/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PatientRole;

import ui.DoctorRole.*;
import business.Doctor.Doctor;
import business.EcoSystem;
import business.Organization.DoctorOrganization;
import business.Patient.Patient;
import business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manal
 */
public class ManagePatientProfile extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorProfile
     */
    private JPanel workArea;
    private DoctorOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private Patient currePatient;
    ArrayList<Doctor> docList;

    public ManagePatientProfile(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();

        this.workArea = userProcessContainer;
        this.business = business;
        this.userAccount = account;
        currePatient = (Patient) userAccount;
        if (currePatient != null) {

            txtName.setText(userAccount.getPerson().getFirstName());
            txtAge.setText(currePatient.getAge());
            txtBp.setText(currePatient.getBp());
            txtLoc.setText(currePatient.getLocation());
            txtPhoneNumber.setText(userAccount.getPerson().getPhoneNumber());
            xtAllergey.setText(currePatient.getAllergy());
            txtEmail.setText(currePatient.getPerson().getEmail());
            passwordTextField.setText(userAccount.getPassword());
           
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        xtAllergey = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateButton.setBackground(new java.awt.Color(94, 92, 230));
        updateButton.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel7.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 140, 39));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Enter Details");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 84, 90));
        jLabel7.setText("Name");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, -1));

        txtAge.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 40));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("Age *");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel7.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 40));

        txtLoc.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 420, 40));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Location *");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, -1));

        jLabel12.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(73, 84, 90));
        jLabel12.setText("Phone Number *");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, -1));

        txtPhoneNumber.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 420, 40));

        jLabel13.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(73, 84, 90));
        jLabel13.setText("Allergy *");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 220, -1));

        xtAllergey.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(xtAllergey, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 420, 40));

        jLabel10.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(73, 84, 90));
        jLabel10.setText("Vitals : Blood Pressue *");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 220, 40));

        txtBp.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        txtBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBpActionPerformed(evt);
            }
        });
        jPanel7.add(txtBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 420, 40));

        txtEmail.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 420, 40));

        passwordTextField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 420, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email *");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patientprofile2.jpg"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 600, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1223, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        Patient patient = (Patient) userAccount;
        System.out.println("**" + patient.getUsername());
        String phoneNumber = txtPhoneNumber.getText();

        String aalergy = xtAllergey.getText();
        String age = txtAge.getText();
        String bp = txtBp.getText();
        String location = txtLoc.getText();
        if (location.isEmpty() || aalergy.isEmpty() || age.isEmpty() || bp.isEmpty() || phoneNumber.isEmpty() || txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        if (!phoneNumber.matches("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(null, " 10 digit phone number");
            txtPhoneNumber.setText("");
            return;
        }

        if (!age.matches("[0-9][0-9]")) {
            JOptionPane.showMessageDialog(null, " Age should be less than 100");
            txtAge.setText("");
            return;
        }
         if (!passwordTextField.getText().matches("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")) {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            passwordTextField.setText("");
            return;
        }
        if (!txtEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {
            JOptionPane.showMessageDialog(null, "Invalid email format");
            // Clear or handle the text field accordingly
             txtEmail.setText("");
            return;
        }
		

        txtName.setText(patient.getPerson().getFirstName());

        patient.setLocation(txtLoc.getText());
        patient.getPerson().setPhoneNumber(txtPhoneNumber.getText());
        patient.setAge(txtAge.getText());
        patient.setBp(txtBp.getText());
        patient.setAllergy(xtAllergey.getText());
        patient.setEmail(txtEmail.getText());
        userAccount.setPassword(passwordTextField.getText());
        JOptionPane.showMessageDialog(null, "Information is Updated.");


    }//GEN-LAST:event_updateButtonActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLoc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField xtAllergey;
    // End of variables declaration//GEN-END:variables
}
