/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Emergency;

import ui.DoctorRole.*;
import business.Doctor.Doctor;
import business.Doctor.DoctorDirectorty;
import business.EcoSystem;
import business.Emergency.Emergency;
import business.Emergency.EmergencyDirectory;
import business.Organization.DoctorOrganization;
import business.Organization.EmergencyOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabTestWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreya
 */
public class EmergencyWorkAreaPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private EmergencyOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private final Emergency loggedInUser;
    Timer timer;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public EmergencyWorkAreaPanel(JPanel workArea, UserAccount account, EmergencyOrganization organization, EcoSystem business) {
        initComponents();

        this.workArea = workArea;
        this.organization = organization;
        this.business = business;
        this.userAccount = account;

        this.loggedInUser = populateUser();
        Time();
    }

    private void Time() {

        Date date = new Date();
        DateFormat timeFormat = new SimpleDateFormat("HH:mm a");
        String time = timeFormat.format(date);
        timeLabel.setText(time);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Appointments = new javax.swing.JPanel();
        manageAppointment = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        profile = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(249, 252, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeLabel.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        timeLabel.setText("3:45 PM");
        jPanel6.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setText("Emergency Dashboard");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(152, 151, 151));
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 100));

        Appointments.setBackground(new java.awt.Color(255, 255, 255));
        Appointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAppointment.setBackground(new java.awt.Color(255, 255, 255));
        manageAppointment.setForeground(new java.awt.Color(255, 255, 255));
        manageAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageAppointment.setPreferredSize(new java.awt.Dimension(100, 48));
        manageAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageAppointmentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageAppointmentMousePressed(evt);
            }
        });
        manageAppointment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Mange  Requests");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        manageAppointment.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, -1));

        Appointments.add(manageAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 70));
        Appointments.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        profile.setPreferredSize(new java.awt.Dimension(100, 48));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Manage Profile");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        profile.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        Appointments.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        rightPanel.setBackground(new java.awt.Color(250, 249, 251));
        rightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Appointments, javax.swing.GroupLayout.DEFAULT_SIZE, 1960, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAppointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppointmentMousePressed
        // TODO add your handling code here:

       //s manageAppointment();
    }//GEN-LAST:event_manageAppointmentMousePressed

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_profileMousePressed

    private void manageAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppointmentMouseClicked
        // TODO add your handling code here:
           addBloodReq();
    }//GEN-LAST:event_manageAppointmentMouseClicked
/**/
    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        // TODO add your handling code here:
           updateProfile();
    }//GEN-LAST:event_profileMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
 addBloodReq();
        //smanageAppointment();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
  updateProfile();
    }//GEN-LAST:event_jLabel5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appointments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel manageAppointment;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    private void updateProfile() {

        manageAppointment.setBackground(new Color(213, 230, 249));

        profile.setBackground(new Color(255, 255, 255));

        ManageEmergencyProfile docProfile = new ManageEmergencyProfile(loggedInUser, userAccount);

        rightPanel.add(docProfile);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

    private Emergency populateUser() {

        EmergencyDirectory directory = organization.getEmergencyDirectory();

        for (Emergency emg : directory.getEmergencyList()) {

            System.out.println("labs " + emg.toString());
            if (emg != null && emg.e.getUserName()!= null && emg.e.getUserName().equals(userAccount.getUsername())) {
                System.out.println("lab matches is " + emg.getEmergencyID());
                return emg;
            }

        }
        return null;

    }
    
    

   

    private void addBloodReq() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        
        manageAppointment.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));

        ViewEmergencyRequestsJPanel viewReqEmg = new ViewEmergencyRequestsJPanel( workArea,  userAccount, organization);
    
        rightPanel.add(viewReqEmg);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }
}
