/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Emergency;

import business.Emergency.Emergency;
import business.Organization.EmergencyOrganization;
import business.Organization.LabOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.Req_Emergency;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrey
 */
public class ViewEmergencyRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmergencyRequestsJPanel
     */
    private JPanel userProcessContainer;

    private UserAccount userAccount;
    private EmergencyOrganization emergencyOrganization;

    public ViewEmergencyRequestsJPanel(JPanel userProcessContainer, UserAccount account, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.emergencyOrganization = (EmergencyOrganization) organization;

        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtablemed = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jtablemed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtablemed.setGridColor(new java.awt.Color(255, 255, 255));
        jtablemed.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jtablemed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablemedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablemed);

        btnProcess.setBackground(new java.awt.Color(255, 55, 95));
        btnProcess.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 55, 95));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("View Emergency Requests");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage_ambul.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcess)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(734, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProcess)
                    .addComponent(jLabel2))
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtablemedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablemedMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jtablemedMouseClicked

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtablemed.getSelectedRow();
        if (selectedRow >= 0) {
            Object selectedObject = jtablemed.getValueAt(selectedRow, 0);
             Req_Emergency request = null;
             if (selectedObject instanceof Req_Emergency) {
                 request = (Req_Emergency) selectedObject;
                if(request.getStatus()!= null && request.getStatus().equals("Completed")){
                     JOptionPane.showMessageDialog(null, "Selected item is already completed.");
                     return ;
                }
             }
            if (selectedObject instanceof Req_Emergency) {
                request = (Req_Emergency) selectedObject;
                
                request.setStatus("Completed");
                
                JOptionPane.showMessageDialog(null, "Request processed successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Selected item is not a Request Emergency.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
        }

    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtablemed.getModel();

        model.setRowCount(0);
        System.out.println("emergencyOrganization.getReqEmgDir().getEmergencyUserList()" + emergencyOrganization);
        for (Req_Emergency request : emergencyOrganization.getReqEmgDir().getEmergencyUserList()) {
            Emergency requestEmg = request.getEmergencyID(); // Get the Lab associated with the request
            // System.out.println("requestLab: " + requestLab);
            //  System.out.println("user name is****" + userAccount.getUsername());
            if (requestEmg != null && requestEmg.e.getUserName().equals(userAccount.getUsername())) {

                //System.out.println("request: " + request);
                Object[] row = new Object[5];
                row[0] = request; // Storing the object reference in row[0]
                row[1] = request.getUserId().getUsername(); // Displayed in the table
                row[2] = request.getLocation(); // Displayed in the table
                row[3] = request.getStatus();

// Add row to the table model
                  model.addRow(row);

            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablemed;
    // End of variables declaration//GEN-END:variables
}
