/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.GovernmentOrganization;

import business.EcoSystem;
import business.Organization.EmergencyOrganization;
import business.Organization.LabOrganization;
import business.Organization.Organization;
import business.WorkQueue.Req_Emergency;
import business.WorkQueue.WorkRequest;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author shrey
 */
public class EmergencyRequestAnalysis extends javax.swing.JFrame {

    private final EcoSystem business;

    /**
     * Creates new form EmergencyRequestAnalysis
     */
     private DefaultCategoryDataset dataset;
    public EmergencyRequestAnalysis(String title, EcoSystem business) {
        super(title);
        this.business = business;
        dataset = createDataset(); // Create dataset with lab request data
        JFreeChart chart = createChart(dataset); // Create bar chart
        ChartPanel chartPanel = new ChartPanel(chart);
        setContentPane(chartPanel);
        initComponents();
    }
    
    private DefaultCategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int completeCount = 0;
        int pendingCount = 0;
        Organization org = null;
        // Assuming labRequestList is a list of LabRequest objects
        for (Organization organization : business.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof EmergencyOrganization) {
                org = organization;
                break;
            }
        }
        if (org != null) {

            org.getEmployeeDirectory().getEmergencyDirectory();
        }
        EmergencyOrganization emrOrg = (EmergencyOrganization) org; // Typecast if necessary
        System.out.println("labOrg" + emrOrg.getReqEmgDir().getEmergencyUserList());

        for (Req_Emergency EmgRequest : emrOrg.getReqEmgDir().getEmergencyUserList()) {
            System.out.println("labRequest" + EmgRequest);
            System.out.println("labRequest" + EmgRequest.getStatus());
            if (EmgRequest.getStatus().equalsIgnoreCase("completed")) {
                completeCount++;
            } else if (EmgRequest.getStatus().equalsIgnoreCase("sent")) {
                pendingCount++;
            }
        }

        // Add counts to the dataset
        dataset.addValue(completeCount, "Status", "Complete");
        dataset.addValue(pendingCount, "Status", "Sent");

        return dataset;
    }

    private JFreeChart createChart(DefaultCategoryDataset dataset) {
        JFreeChart chart = ChartFactory.createBarChart(
                "Lab Request Analysis", // Chart title
                "Status", // X-axis label
                "Number of Requests", // Y-axis label
                dataset // Dataset
        );
        return chart;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
