/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.GovernmentOrganization;

import business.EcoSystem;
import business.Organization.Organization;
import business.Patient.Patient;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import business.Patient.PatientDirectorty;
import business.UserAccount.UserAccount;

/**
 *
 * @author shrey
 */
public class PatientDataAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form PatientDataAnalysis
     */
    private DefaultCategoryDataset dataset;
    private EcoSystem business;
    private Patient currePatient;
    public PatientDataAnalysis(String title, EcoSystem business) {

        super(title);
        this.business = business;
        dataset = createDataset(); // Create dataset with patient data
        JFreeChart chart = createChart(dataset); // Create bar chart
        ChartPanel chartPanel = new ChartPanel(chart);
        setContentPane(chartPanel);
        initComponents();
    }

    private DefaultCategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Replace this with your patient data
        ArrayList<UserAccount> account = business.getAccountDirectory().getUserAccountList();
        // ArrayList<Patient> patientRecord =  
        for (UserAccount o : account) {
            currePatient = (Patient) o;
            int age = 0;
            System.out.println("o.role" + o.getRole());
            if(currePatient.getAge()!=null)
             age = Integer.parseInt(currePatient.getAge()); // Assuming you have a method getAge() in Patient class
            String allergies = currePatient.getAllergy(); // Assuming you have a method getAllergies() in Patient class
            int bp = 0;
            if(currePatient.getBp()!=null)
             bp = Integer.parseInt(currePatient.getBp()); // Assuming you have a method getBloodPressure() in Patient class
            String location = currePatient.getLocation(); // Assuming you have a method getLocation() in Patient class

            dataset.addValue(age, "Age", "Patient " + currePatient.getUsername()); // Age data
            dataset.addValue(bp, "Blood Pressure", "Patient " + currePatient.getUsername()); // Blood Pressure data


        }

        

        // Add more patient data as needed
        return dataset;
    }

    private JFreeChart createChart(DefaultCategoryDataset dataset) {
        JFreeChart chart = ChartFactory.createBarChart(
                "Patient Data Analysis", // Chart title
                "Age Groups", // X-axis label
                "Number of Patients", // Y-axis label
                dataset // Dataset
        );
        return chart;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
