/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeRole;

import ui.DoctorRole.*;
import business.Doctor.Doctor;
import business.Doctor.DoctorDirectorty;
import business.EcoSystem;
import business.Organization.DoctorOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabTestWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kunal
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private DoctorOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private Doctor currentDoctor;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.workArea = userProcessContainer;
        this.business = business;
        Time();
    }
    
    private void Time() {
       
                Date date= new Date();
                DateFormat timeFormat =  new SimpleDateFormat("HH:mm a");
                String time = timeFormat.format(date);
                timeLabel.setText(time);
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Appointments = new javax.swing.JPanel();
        manageEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        requesLab1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        manageUsers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageOrganizations = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rightPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeLabel.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        timeLabel.setText("3:45 PM");
        jPanel6.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setText("Dashboard");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(152, 151, 151));
        jLabel1.setText("Manage everything related to community health network");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 100));

        Appointments.setBackground(new java.awt.Color(255, 255, 255));
        Appointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEmployee.setBackground(new java.awt.Color(255, 255, 255));
        manageEmployee.setPreferredSize(new java.awt.Dimension(100, 48));
        manageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageEmployeeMousePressed(evt);
            }
        });
        manageEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Manage Employees");
        manageEmployee.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, -1));

        requesLab1.setBackground(new java.awt.Color(255, 255, 255));
        requesLab1.setPreferredSize(new java.awt.Dimension(100, 48));
        requesLab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                requesLab1MousePressed(evt);
            }
        });
        requesLab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Request Lab");
        requesLab1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        manageEmployee.add(requesLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 60));

        Appointments.add(manageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 60));

        manageUsers.setBackground(new java.awt.Color(255, 255, 255));
        manageUsers.setPreferredSize(new java.awt.Dimension(100, 48));
        manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageUsersMousePressed(evt);
            }
        });
        manageUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Manage Users");
        manageUsers.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 20, 180, -1));

        Appointments.add(manageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        manageOrganizations.setBackground(new java.awt.Color(255, 255, 255));
        manageOrganizations.setPreferredSize(new java.awt.Dimension(100, 48));
        manageOrganizations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageOrganizationsMousePressed(evt);
            }
        });
        manageOrganizations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("Mange Organizations");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        manageOrganizations.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        Appointments.add(manageOrganizations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 60));
        Appointments.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        rightPanel.setBackground(new java.awt.Color(250, 249, 251));
        rightPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Appointments, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsersMousePressed

        manageUsers();
    }//GEN-LAST:event_manageUsersMousePressed

    private void manageEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeMousePressed
        // TODO add your handling code here:
        //   requestBlood();
        manageEmployees();
    }//GEN-LAST:event_manageEmployeeMousePressed

    private void manageOrganizationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationsMousePressed
        // TODO add your handling code here:

        manageOrganizations();
    }//GEN-LAST:event_manageOrganizationsMousePressed

    private void requesLab1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requesLab1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_requesLab1MousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        manageOrganizations();
    }//GEN-LAST:event_jLabel9MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appointments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel manageEmployee;
    private javax.swing.JPanel manageOrganizations;
    private javax.swing.JPanel manageUsers;
    private javax.swing.JPanel requesLab1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    
    private void manageEmployees() {
        manageUsers.setBackground(new Color(213, 230, 249));
        manageEmployee.setBackground(new Color(255, 255, 255));
        manageOrganizations.setBackground(new Color(213, 230, 249));
        //profile.setBackground(new Color(213, 230, 249));

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(workArea, business.getOrganizationDirectory(), business);

        rightPanel.add(manageEmployeeJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }

    private void manageOrganizations() {

        manageUsers.setBackground(new Color(213, 230, 249));
        manageOrganizations.setBackground(new Color(255, 255, 255));
        manageEmployee.setBackground(new Color(213, 230, 249));
      //  profile.setBackground(new Color(213, 230, 249));

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(workArea, business.getOrganizationDirectory(), business);

        rightPanel.add(manageOrganizationJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

    private void manageUsers() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        manageOrganizations.setBackground(new Color(213, 230, 249));
        manageUsers.setBackground(new Color(255, 255, 255));
        manageEmployee.setBackground(new Color(213, 230, 249));
     //   profile.setBackground(new Color(213, 230, 249));

        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(workArea, business);
        rightPanel.add(muajp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }
}
