/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.LabAssistantRole;

import business.Lab.Lab;
import business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author shrey
 */
public class ManageLabProfile extends javax.swing.JPanel {

    /**
     * Creates new form ManageLabProfile
     */
    JPanel CardSequencePanel;
    Lab lab;
    UserAccount user;
    public ManageLabProfile(Lab lab, UserAccount user) {
        initComponents();
        this.lab = lab;
        this.user = user;
         System.out.println("this.lab "+this.lab );
        populateUser();
  }

    public void populateUser(){
        System.out.println("inside populateUser");
         jTextField1.setText(lab.getLabName()); // Set the text to lab name or some default text
         txtLocation.setText(lab.getLocation());
         txtPhoneNumber.setText(lab.getPhoneNumber());
         txtEmail.setText(lab.getEmail());
         passwordTextField.setText(user.getPassword());
    // txtLocation.setText(lab.getLocation());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightpane = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        rightpane.setBackground(new java.awt.Color(255, 255, 255));
        rightpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateButton.setBackground(new java.awt.Color(94, 92, 230));
        updateButton.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        rightpane.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 140, 39));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Enter Details");
        rightpane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 84, 90));
        jLabel7.setText("Name");
        rightpane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, -1));

        txtLocation.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        rightpane.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 40));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("Location *");
        rightpane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        jLabel12.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(73, 84, 90));
        jLabel12.setText("Phone Number *");
        rightpane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, -1));

        txtPhoneNumber.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        rightpane.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 420, 40));

        jTextField1.setEditable(false);
        rightpane.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email *");
        rightpane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, -1));

        txtEmail.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        rightpane.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 400, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        rightpane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 20));

        passwordTextField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        rightpane.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor-3d-icon-illustration-free-png.png"))); // NOI18N
        rightpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rightpane, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        if (txtPhoneNumber.getText().isEmpty() || txtEmail.getText().isEmpty() || txtLocation.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        if (!txtPhoneNumber.getText().matches("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(null, " 10 digit phone number");
            txtPhoneNumber.setText("");
            return;
        }
        if (!passwordTextField.getText().matches("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")) {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            passwordTextField.setText("");
            return;
        }
        if (!txtEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {
            JOptionPane.showMessageDialog(null, "Invalid email format");
            // Clear or handle the text field accordingly
             txtEmail.setText("");
            return;
        }
        
        lab.setLocation(txtLocation.getText());
        lab.setPhoneNumber(txtPhoneNumber.getText());
        lab.setEmail(txtEmail.getText());
        user.setPassword(passwordTextField.getText());
        JOptionPane.showMessageDialog(null, "Information Updated");
        
        
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel rightpane;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
