/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.blood;

import business.BloodBank.BloodBank;
import business.BloodBank.BloodDirectory;
import ui.DoctorRole.*;
import business.Doctor.Doctor;
import business.Doctor.DoctorDirectorty;
import business.EcoSystem;
import business.Organization.BloodOrganization;
import business.Organization.DoctorOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabTestWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class BloodOrgWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private BloodOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private BloodBank currentBloodBank;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public BloodOrgWorkAreaJPanel(JPanel workArea, UserAccount account, BloodOrganization organization, EcoSystem business) {
        initComponents();

        this.workArea = workArea;
        this.organization = organization;
        this.business = business;
        this.userAccount = account;

        currentBloodBank = populateBloodBank();
        
        Time();
    }
    
    
     private void Time() {
       
                Date date= new Date();
                DateFormat timeFormat =  new SimpleDateFormat("HH:mm a");
                String time = timeFormat.format(date);
                timeLabel.setText(time);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Appointments = new javax.swing.JPanel();
        manageBloodBank = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageDoctorRequest = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        patientRequest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeLabel.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        timeLabel.setText("3:45 PM");
        jPanel6.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setText("Blood Organization Dashboard");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel7.setText("jLabel6");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        Appointments.setBackground(new java.awt.Color(255, 255, 255));
        Appointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBloodBank.setBackground(new java.awt.Color(255, 255, 255));
        manageBloodBank.setPreferredSize(new java.awt.Dimension(100, 48));
        manageBloodBank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageBloodBankMousePressed(evt);
            }
        });
        manageBloodBank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Manage Blood Bank");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        manageBloodBank.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        Appointments.add(manageBloodBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 60));

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setPreferredSize(new java.awt.Dimension(100, 48));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
        });
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Manage Profile");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        profile.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        Appointments.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        manageDoctorRequest.setBackground(new java.awt.Color(255, 255, 255));
        manageDoctorRequest.setPreferredSize(new java.awt.Dimension(100, 48));
        manageDoctorRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageDoctorRequestMousePressed(evt);
            }
        });
        manageDoctorRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Mange Doctor Request");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        manageDoctorRequest.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        Appointments.add(manageDoctorRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 60));
        Appointments.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        patientRequest.setBackground(new java.awt.Color(255, 255, 255));
        patientRequest.setPreferredSize(new java.awt.Dimension(100, 48));
        patientRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientRequestMousePressed(evt);
            }
        });
        patientRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Manage Patient Request");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        patientRequest.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 40));

        Appointments.add(patientRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 60));

        rightPanel.setBackground(new java.awt.Color(250, 249, 251));
        rightPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blood bank.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rightPanel.add(jLabel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addComponent(Appointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        // TODO add your handling code here:
        //ad  appointments();

        updateProfile();
    }//GEN-LAST:event_profileMousePressed

    private void manageBloodBankMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBloodBankMousePressed

        manageBloodBank();
    }//GEN-LAST:event_manageBloodBankMousePressed

    private void manageDoctorRequestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDoctorRequestMousePressed
        // TODO add your handling code here:

        manageDoctorRequest();
    }//GEN-LAST:event_manageDoctorRequestMousePressed

    private void patientRequestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientRequestMousePressed
        // TODO add your handling code here:

        managePatientRequest();
    }//GEN-LAST:event_patientRequestMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        updateProfile();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        manageDoctorRequest();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
      //  managePatientRequest();
      manageBloodBank();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
         managePatientRequest();
    }//GEN-LAST:event_jLabel4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appointments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel manageBloodBank;
    private javax.swing.JPanel manageDoctorRequest;
    private javax.swing.JPanel patientRequest;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    private void updateProfile() {
        profile.setBackground(new Color(255, 255, 255));
        manageBloodBank.setBackground(new Color(213, 230, 249));
        manageDoctorRequest.setBackground(new Color(213, 230, 249));
        patientRequest.setBackground(new Color(213, 230, 249));

        ManageBloodBankProfile mangbp = new ManageBloodBankProfile(currentBloodBank, userAccount);

        rightPanel.add(mangbp);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

    private BloodBank populateBloodBank() {

        BloodDirectory directory = organization.getBloodDirectory();
        System.out.println("ui.DoctorRole.DoctorWorkAreaJPanel.populateDoctor()" + userAccount.getUsername());
        for (BloodBank bloodBank : directory.getBloodBankArrayList()) {
            if (bloodBank !=null && bloodBank.e != null && bloodBank.e.getUserName()!=null && bloodBank.e.getUserName().equals(userAccount.getUsername())) {
                System.out.println("Doctor found: " + bloodBank.e.getName());
                return bloodBank;
            }
        }

        System.out.println("Doctor not found");
        return null;

    }

    private void manageBloodBank() {

        manageBloodBank.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));
        manageDoctorRequest.setBackground(new Color(213, 230, 249));
        patientRequest.setBackground(new Color(213, 230, 249));

        ManageBloodBanks mbb = new ManageBloodBanks(workArea, userAccount, business, currentBloodBank);

        rightPanel.add(mbb);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

    private void manageDoctorRequest() {
        //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        manageDoctorRequest.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));
        manageBloodBank.setBackground(new Color(213, 230, 249));
        patientRequest.setBackground(new Color(213, 230, 249));

        ProcessOrderForDoctor mbb = new ProcessOrderForDoctor(workArea, userAccount, business, currentBloodBank);

        rightPanel.add(mbb);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

    private void managePatientRequest() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        patientRequest.setBackground(new Color(255, 255, 255));
        profile.setBackground(new Color(213, 230, 249));
        manageDoctorRequest.setBackground(new Color(213, 230, 249));
        manageBloodBank.setBackground(new Color(213, 230, 249));

        ManagePatientBloodDonationRequest mpdr = new ManagePatientBloodDonationRequest(workArea, userAccount, business, currentBloodBank);

        rightPanel.add(mpdr);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }

}
