/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.blood;

import business.BloodBank.BloodBank;

import business.Doctor.Doctor;
import business.EcoSystem;
import business.UserAccount.UserAccount;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author manal
 */
public class ManageBloodBankProfile extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorProfile
     */
    BloodBank bloodBank;
    private final UserAccount account;

    public ManageBloodBankProfile(BloodBank bb, UserAccount account) {
        initComponents();
        this.bloodBank = bb;
        this.account = account;
        txtName.setText(bloodBank.e.getName());
        txtLicense.setText(bloodBank.getLicence());
        txtPhoneNumber.setText(bloodBank.getPhoneNumber());
        txtLocation.setText(bloodBank.getLocation());
        txtEmail.setText(bloodBank.getEmail());
        passwordTextField.setText(account.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateButton.setBackground(new java.awt.Color(255, 55, 95));
        updateButton.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel7.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 39));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Enter Details");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 84, 90));
        jLabel7.setText("Name");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, -1));

        txtLocation.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 40));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("Location *");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel7.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 40));

        txtLicense.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 420, 40));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Licience *");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, -1));

        jLabel13.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(73, 84, 90));
        jLabel13.setText("Phone Number *");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 220, -1));

        txtPhoneNumber.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 420, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email *");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, -1));

        txtEmail.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 400, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 100, 20));

        passwordTextField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blood icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        String licence = txtLicense.getText();
        String location = txtLocation.getText();

        String phoneNumber = txtPhoneNumber.getText();

        System.out.println("6666" + phoneNumber.length());

        if (licence.isEmpty() || location.isEmpty() || phoneNumber.isEmpty() || txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        if (!phoneNumber.matches("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(null, " 10 digit phone number");
            txtPhoneNumber.setText("");
            return;
        }
        if (!passwordTextField.getText().matches("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$")) {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            passwordTextField.setText("");
            return;
        }
        if (!txtEmail.getText().matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}")) {
            JOptionPane.showMessageDialog(null, "Invalid email format");
            // Clear or handle the text field accordingly
            txtEmail.setText("");
            return;
        }

        if (bloodBank != null) {

            bloodBank.setLicence(licence);
            bloodBank.setLocation(location);
            bloodBank.setPhoneNumber(phoneNumber);
            bloodBank.setEmail(txtEmail.getText());
            account.setPassword(passwordTextField.getText());
            JOptionPane.showMessageDialog(null, "Information Updated.");

        }

        if (bloodBank.getId() == null) {
            Random random = new Random();
            int randomId = 1 + random.nextInt(100);
            System.out.println("bb :"+"B_" + randomId);
            bloodBank.setId("B_" + randomId);
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
